NoConsoleOutput: false
DEBUG: false

#Illegal block preventions
PreventPlacingIllegalBlocks: true
RemoveIllegalBlockOnPlace: true
RemoveIllegalBlocksOnInteract: true
RemoveIllegalBlocksOnJoin: true
RemoveIllegalBlocksOnInventoryOpen: true
RemoveIllegalBlocksOnDrop: true
RemoveIllegalBlocksOnClick: true
RemoveIllegalBlocksOnPickup: true
RemoveIllegalBlocksOnMove: true
#Remove illegal blocks on chunkload, useful if players have placed a lot of bedrock/other blocks and you want to get rid of it
RemoveALLIllegalBlocksOnCHUNKLOAD: false

#Bugfixes
PreventEndGatewayCrashExploit: true
PreventDestroyingEndPortals: true
FillInBedrockFloor: true
FillInBedrockRoof: true
PreventGoingBelowBedrockFloorOnElytra: true
DisableAllElytras: false
DisableWithers: false

#Dupe preventions
DisableChestsOnDonkeys: false
PreventDonkeysFromGoingThroughPortals: false

#List of banned blocks.
#WARNING: ADDING MOB SPAWNER TO THIS LIST WHILE HAVING RemoveALLIllegalBlocksOnCHUNKLOAD ENABLED WILL REMOVE ALL MOB SPAWNERS IN YOUR WORLD.
#You can also add non blocks and they should get removed aswell.
BANNED_BLOCKS:
  - BEDROCK
  - BARRIER
  - COMMAND
  - STRUCTURE_BLOCK
  - MONSTER_EGG

#The item banned blocks are replaced with.
Replacement_Item: STONE



# 1b1t options
AllowBreakingBedrock: false
1b1tPlaceBedrock: false


# DISABLE STUFF AT CERTAIN TPS
# SET TO -1 TO DISABLE.
Redstone: 16
Elytra: 13
mobAI: 17
Explosions: 17
