config-version: 1.0

language:
  default-language: en-us
  # if set to true, will display language based on client locale
  auto-language: true

illegals:
  illegal-blocks:
    prevent-placing: true
    remove-on-place: true
    remove-on-interact: true
    remove-on-join: true
    remove-on-inventory-open: true
    remove-on-drop: true
    remove-on-click: true
    remove-on-pickup: true
    remove-on-move: true
    # Please note this may lower tps slightly (or heavily if players have big stashes)
    remove-on-chunkload: false
    banned-blocks:
      - BEDROCK
      - BARRIER
      - COMMAND
      - STRUCTURE_BLOCK
      - ENDER_PORTAL_FRAME
    replacement-item: STONE # The item banned blocks are replaced with.
    disable-banned-blocks-warning: false
  illegal-items:
    remove-spawn-eggs: true
    revert-stacked-items:
      enable: true
      only-for-certain-items: false
      certain-items:
        - "TOTEM"
    revert-enchanted-items: true
    revert-unenchantable: true
    revert-specific-enchantments:
      enable: false
      enchantments:
        - "DIG_SPEED"
      exempted-items:
        - "GOLDEN_APPLE"
    revert-specific-data-values:
      enable: true
      revert-illegal-golden-apple: true
      data-values:
        - "SuperIllegalItem(0)"
    revert-unbreakables:
      enable: true
      enable-whitelist: false
      whitelisted-items:
        - "DIAMOND_CHESTPLATE"
      skip-zero-durability: true
    banned-names: # Remove items that were custom named to a specific string. Suggested by STORMIN.
      - "Super Insane Mega Sussy Item" # case sensitive
  illegal-heads:
    remove-illegal-heads: true
    # NOT RECOMMENDED TO TURN ON, RAPES TPS!
    remove-on-chunkload: false

patches:
  prevent-nocom-coordinate-exploit:
    enable: true
    nocom-max-distance: 64
  prevent-teleport-coordinate-exploit:
    enable: true
    teleport-vanish-time-in-ticks: 10
    min-distance-to-vanish-player: 100
  prevent-crafting-recipe-lag-exploit:
    enable: true
    crafting-recipe-delay-in-ticks: 5
  limit-projectiles:
    max-per-time: 3
    time-in-ticks: 10
    # 3 projectiles can be sent every 10 ticks (0.5 seconds)
  prevent-burrow:
    enable: true
    burrow-damage-when-moving: 1
    teleport-above: true
    prevent-if-block-above: false
    break-anvil-instead-of-teleport: true
    allow-slabs-in-burrow: true
  prevent-book-ban:
    enable: true
    max-byte-size-per-page: 255
  prevent-chunk-ban: true
  prevent-end-gateway-crash-exploit: true
  prevent-dispenser-crash-exploit: true
  prevent-snowball-exploit: true
  prevent-fireworks-in-portals: true
  prevent-dropped-items-in-portals: true
  prevent-all-entities-in-portals: true
  prevent-destroying-end-portals: true
  prevent-multiple-enderdragons: true
  prevent-portal-traps: false
  prevent-invalid-names: true
  prevent-command-sign: true

chunk-limits:
  max-blocks-per-chunk:
    enable: true
    blocks:
      ENCHANTMENT_TABLE:16
      ENDER_CHEST:64
      CHEST:500
      DISPENSER:100
      TRAPPED_CHEST:200
      SIGN:100
      SLIME_BLOCK:128
      BEACON:32
      PISTON_BASE:32
      PISTON_EXTENSION:32
      PISTON_MOVING_PIECE:32
      PISTON_STICKY_BASE:32
      GLOWSTONE:99999
      BANNER:100
      SKULL:50
      SKULL_ITEM:50

chat:
  replace-@: true
  prevent-unicode-dot: true
  character-limit:
    enable: true
    log: true
    char-limit: 128
  links:
    prevent-sending:
      enable: false
      log: true
      only-for-players-around-spawn: true
      spawn-radius: 1000
    prevent-spamming:
      enable: true
      delay-until-next-link-in-seconds: 300
      only-for-players-around-spawn: true
      spawn-radius: 1000
    link-regex:
      - "(https?://(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?://(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})"
      - "[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z()]{1,6}\\b([-a-zA-Z()@:%_+.~#?&/=]*)"
    more-lenient-link-check:
      enable: true
      exemptions:
        - "discord"
        - "dc"
  banned-words:
    enable: false
    log: true
    banned-words:
      - "what's 2+2"
  banned-regex:
    enable: false
    log: true
    banned-regex:
      - "^This is a(.*)banned message" # Prevents any message that starts with "This is a" and ends with "banned message"
  prevent-spam:
    enable: true
    anti-spam-time: 1 # 1 message per second
    # How many messages should we allow to send in x seconds (converted to ticks)
    anti-spam-check-time: 30
    anti-spam-messages-per-time: 10 # ~1 message every 3 seconds if constantly spamming
    anti-spam-word-time: 60
    anti-spam-commands:
      enable: true # Use the same antispam options for commands as well.
      use-whitelist: true # Exclude commands from antispam.
      whitelist:
        - /msg
        - /message
        - /w
        - /whisper
        - /tell
        - /r
        - /reply

command-whitelist:
  # This will make it pretty much impossible to find your plugins as only the commands you specify will be able to work.
  # allow bypass using permission: anarchyexploitfixes.commandwhitelistbypass
  enable: true
  use-as-blacklist-instead: false
  commands:
    - /help
    - /msg
    - /kill
    - /discord
    - /togglechat
    - /toggletells
    - /ignore
    - /ignorelist
    - /toggledeathmsg
    - /stats
    - /tps
    - /w
    - /m
    - /t
    - /pm
    - /tell
    - /whisper
    - /r
    - /reply

join-leave-messages:
  enable: true
  connection-messages-on-by-default: true # /toggleconnectionmsgs
  # If you want to hide yourself or someone else when logging into the game, just give these permissions:
  #  anarchyexploitfixes.silentJoin, anarchyexploitfixes.silentLeave
  first-join-messages:
    enable: false

elytra:
  # Patches the future/rusherhack/kamiblue 2b2t elytra fly exploit
  patch-packet-elytrafly: false
  only-kick-on-packet-elytrafly: false #If enabled, the plugin will not remove elytra from the player, but simply disconnect from the server.
  packet-elytrafly-actionbar-notification:
    enabled: true
  # Recommended to not go lower as there could be false positives.
  MaxElytraOpensPer10Seconds: 25 # Will only allow players to go about 85km/h on kami blue, and won't even work on rusherhack.
  elytra-speed:
    # set nocheatplus elytra settings to 999999
    display-actionbar: true
    display-chunk-info-in-actionbar: true
    Nether-Ceiling:
      enable: true
      deny-elytra-usage: false
      speed-old-chunks: 0.5
      speed-new-chunks: 0.5
      enable-bursting: false
      burst-speed-old-chunks: 1.0
      burst-speed-old-chunk-TPS: 18
      burst-speed-new-chunks: 1.0
      burst-speed-new-chunk-TPS: 18
      disable-elytra-on-low-TPS: true
      disable-elytra-TPS: 12
    Everywhere-Else:
      enable: true
      deny-elytra-usage: false
      speed-old-chunks: 1.81 # 130km/h
      speed-new-chunks: 1.81 # 130km/h
      enable-bursting: true
      burst-speed-old-chunks: 5.0 # 357km/h
      burst-speed-old-chunk-TPS: 18
      burst-speed-new-chunks: 3.12 # 223km/h
      burst-speed-new-chunk-TPS: 19
      disable-elytra-on-low-TPS: true
      disable-elytra-TPS: 12
    At-Spawn:
      enable: false
      deny-elytra-usage: false
      radius: 3000
      speed-old-chunks: 1.0
      speed-new-chunks: 0.8
      disable-elytra-on-low-TPS: true
      disable-elytra-TPS: 10

1b1t-options:
  enable-slowdupe: false
  allow-breaking-bedrock: false
  1b1t-place-bedrock: false
  use-spark-health: false
  nick-reset-only: false
  distance-away-to-teleport:
    enable: false
    distance-in-blocks: 5000
    teleport-commands:
      - /tpa
      - /tpahere
      - /call
      - /ecall
      - /etpa
      - /tpask
      - /etpask
    excluded-worlds:
      - world_the_end
      - exampleworld2
  make-specific-commands-hurt-you:
    enable: false
    hurt-commands:
      - /tpa
  disable-ncp-geyser: false
  bypass-slots: false