illegals:
  illegal-blocks:
    prevent-placing: true
    remove-on-place: true
    remove-on-interact: true
    remove-on-join: true
    remove-on-inventory-open: true
    remove-on-drop: true
    remove-on-click: true
    remove-on-pickup: true
    remove-on-move: true
    # Please note this may lower tps slightly (or heavily if players have big stashes)
    remove-on-chunkload: false
    banned-blocks:
      - BEDROCK
      - BARRIER
      - COMMAND
      - STRUCTURE_BLOCK
      - ENDER_PORTAL_FRAME
    replacement-item: STONE # The item banned blocks are replaced with.
    disable-banned-blocks-warning: false
  illegal-items:
    remove-spawn-eggs: true
    revert-stacked-items:
      enable: true
      only-for-certain-items: false
      certain-items:
        - "TOTEM"
    revert-enchanted-items: true
    revert-unenchantable: true
    revert-specific-enchantments:
      enable: false
      enchantments:
        - "DIG_SPEED"
      exempted-items:
        - "GOLDEN_APPLE"
    revert-specific-data-values:
      enable: true
      revert-illegal-golden-apple: true
      data-values:
        - "SuperIllegalItem(0)"
    revert-unbreakables:
      enable: true
      enable-whitelist: false
      whitelisted-items:
        - "DIAMOND_CHESTPLATE"
      skip-zero-durability: true
    banned-names: # Remove items that were custom named to a specific string. Suggested by STORMIN.
      - "Super Insane Mega Sussy Item" # case sensitive
  illegal-heads:
    remove-illegal-heads: true
    # NOT RECOMMENDED TO TURN ON, RAPES TPS!
    remove-on-chunkload: false

patches:
  prevent-nocom-coordinate-exploit:
    enable: true
    nocom-max-distance: 64
  prevent-teleport-coordinate-exploit:
    enable: true
    teleport-vanish-time-in-ticks: 10
    min-distance-to-vanish-player: 100
  prevent-crafting-recipe-lag-exploit:
    enable: true
    crafting-recipe-delay-in-ticks: 5
  limit-projectiles:
    max-per-time: 3
    time-in-ticks: 10
    # 3 projectiles can be sent every 10 ticks (0.5 seconds)
  prevent-burrow:
    enable: true
    burrow-damage-when-moving: 1
    teleport-above: true
    prevent-if-block-above: false
    break-anvil-instead-of-teleport: true
    allow-slabs-in-burrow: true
  prevent-book-ban:
    enable: true
    max-byte-size-per-page: 255
  prevent-chunk-ban: true
  prevent-end-gateway-crash-exploit: true
  prevent-dispenser-crash-exploit: true
  prevent-snowball-exploit: true
  prevent-fireworks-in-portals: true
  prevent-dropped-items-in-portals: true
  prevent-all-entities-in-portals: true
  prevent-destroying-end-portals: true
  prevent-multiple-enderdragons: true
  prevent-portal-traps: false
  prevent-invalid-names: true
  prevent-command-sign: true

chunk-limits:
  max-blocks-per-chunk:
    enable: true
    blocks:
      ENCHANTMENT_TABLE:16
      ENDER_CHEST:64
      CHEST:500
      DISPENSER:100
      TRAPPED_CHEST:200
      SIGN:100
      SLIME_BLOCK:128
      BEACON:32
      PISTON_BASE:32
      PISTON_EXTENSION:32
      PISTON_MOVING_PIECE:32
      PISTON_STICKY_BASE:32
      GLOWSTONE:99999
      BANNER:100
      SKULL:50
      SKULL_ITEM:50

chat:
  replace-@: true
  prevent-unicode-dot: true
  character-limit:
    enable: true
    log: true
    char-limit: 128
  links:
    prevent-sending:
      enable: false
      log: true
      only-for-players-around-spawn: true
      spawn-radius: 1000
    prevent-spamming:
      enable: true
      delay-until-next-link-in-seconds: 300
      only-for-players-around-spawn: true
      spawn-radius: 1000
    link-regex:
      - "(https?://(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?://(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})"
      - "[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z()]{1,6}\\b([-a-zA-Z()@:%_+.~#?&/=]*)"
    more-lenient-link-check:
      enable: true
      exemptions:
        - "discord"
        - "dc"
  banned-words:
    enable: false
    log: true
    banned-words:
      - "what's 2+2"
  banned-regex:
    enable: false
    log: true
    banned-regex:
      - "^This is a(.*)banned message" # Prevents any message that starts with "This is a" and ends with "banned message"
  prevent-spam:
    enable: true
    anti-spam-time: 1 # 1 message per second
    # How many messages should we allow to send in x seconds (converted to ticks)
    anti-spam-check-time: 30
    anti-spam-messages-per-time: 10 # ~1 message every 3 seconds if constantly spamming
    anti-spam-word-time: 60
    anti-spam-commands:
      enable: true # Use the same antispam options for commands as well.
      use-whitelist: true # Only enable antispam for commands specified below.
      whitelist:
        - /msg
        - /message
        - /w
        - /whisper
        - /tell
        - /r
        - /reply

command-whitelist:
  # This will make it pretty much impossible to find your plugins as only the commands you specify will be able
  # to work. Any other commands will show "Bad command. Type /help for all commands."
  enable: true
  allow-OP-to-bypass: true
  commands:
    - /help
    - /msg
    - /kill
    - /discord
    - /togglechat
    - /toggletells
    - /ignore
    - /ignorelist
    - /toggledeathmsg
    - /stats
    - /tps
    - /w
    - /m
    - /t
    - /pm
    - /tell
    - /whisper
    - /r
    - /reply


join-leave-messages:
  enable: true
  join-message: "&7%player% joined the game."
  leave-message: "&7%player% left the game."
  # If you want to hide yourself or someone else when logging into the game, just give these permissions:
  #  anarchyexploitfixes.silentJoin
  #  anarchyexploitfixes.silentLeave
  connection-messages-on-by-default: true # /toggleconnectionmsgs
  first-join-messages:
    enable: false
    first-join-message: "&7%player% joined the game for the first time. They are %players_num% to join." # %players_num% is how many players have joined the server + the current one (ex. 351th)