language:
  default-language: en_us
  # if set to true, will display language based on client locale
  auto-language: true

general:
  # Use only if you are having problems with ProtocolLib when starting the plugin
  disable-all-ProtocolLib: false

misc:
  join-leave-messages:
    enable: true
    connection-messages-on-by-default: true
    # If you want to hide yourself or someone else when logging into the game, just give these permissions:
    # anarchyexploitfixes.silentJoin, anarchyexploitfixes.silentLeave
    first-join-messages:
      enable: false
  kicks:
    mask-kick-messages: false
    prevent-spam-kick:
      enable: false
      kick-messages-to-listen-to:
        - 'Kicked for spamming'
        - 'Stop spamming!'

patches:
  prevent-command-sign: true
  crash-exploits:
    prevent-dispenser-crash:
      enable: true
      log: true
    prevent-end-gateway-crash:
      enable: true
      log: true
    prevent-multiple-enderdragons:
      enable: true
      log: true
  prevent-nocom-coordinate-exploit:
    enable: true
    nocom-max-distance: 64
  prevent-teleport-coordinate-exploit:
    enable: true
    teleport-vanish-time-in-ticks: 10
    min-distance-to-vanish-player: 100
  prevent-crafting-recipe-lag-exploit:
    enable: true
    crafting-recipe-delay-in-ticks: 5
  prevent-bow-bomb:
    enable: true
    # Fully pulled bow is ~9-10. 15 is default just to be safe.
    max-bow-squared-velocity: 15
  prevent-burrow:
    enable: true
    damage-when-moving: 1.0
    teleport-above-block: true
    prevent-if-block-above-burrow: false
    break-anvil-instead-of-teleport: true
    allow-slabs-in-burrow: true
  prevent-book-ban:
    enable: true
    # Per page - Not recommended to touch this
    max-byte-size-per-page: 255
  boatfly-patch:
    # Patch futureclient/rusherhack boat fly exploit
    # This does not affect boats at all! Even on land.
    enable: true
    log: true
    # Only counts for boats
    max-entity-packets-per-10s: 15
  packetfly-patch:
    # Patch future/rusher packet fly
    enable: true
    log: true
    # This is how the packet fly works, 25 is usually fine, if you go lower players may get stuck.
    max-teleport-packets-per-10s: 25
  prevent-snowball-exploit:
    enable: false
    projectile-max-per-time: 3
    projectile-time-in-ticks: 10
    # 3 projectiles can be sent every 10 ticks (0.5 seconds)
  prevent-destroying-end-portals:
    enable: true
    log: true
  prevent-invalid-names:
    enable: true
    log: true
  # Removes entities or players if "invalid", not sure if this works.
  experimental-godmode-patch: false

preventions:
  prevent-opped-players:
    # Checks if a player is op and deops them if they are.
    enable: false
    log: true
    whitelisted-players:
      - Notch
  prevent-non-survival-players:
    # Checks if a player is not in survival and sets them to survival if theyre not.
    enable: false
    log: true
    whitelisted-players:
      - Notch
  disable-explosions-on-low-tps:
    enable: true
    disable-TPS: 14.0
  prevent-nether-roof:
    enable: true
  anti-bed-trap:
    enable: true
    log: false
    death-amount: 2 # x deaths in 30 secs will reset someone's bed.
    check-time-in-seconds: 30
  prevent-ambient-fish-spawns:
    # Prevent the 1.13+ fish from spawning, there is a shit ton of them that spawn
    # which can cause a ton of lag, automatically disabled in 1.12
    enable: false
    fish-types-to-prevent:
      - COD
      - SALMON
      - PUFFERFISH
      - TROPICAL_FISH
  nether-portals:
    # Patches a lag exploit
    prevent-fireworks-in-portals: true
    # May prevent a lag exploit. Disables some Chunkloader designs.
    prevent-dropped-items-in-portals: false
    # Prevent projectiles such as xp bottles and snowballs from going through portals,
    # this can cause a shit ton of lag especially if there is new chunks on the other end, this won't prevent mobs or items
    prevent-projectiles-in-portals: false
    # Only enable if you must... Players are not affected.
    prevent-all-entities-in-portals: false
    # Teleports player to previous location if they keep standing inside a portal for
    # 300 Ticks (15 Seconds)
    prevent-portal-traps: false
  withers:
    disable-withers-from-shooting-skulls: false
    remove-flying-wither-skulls:
      on-chunk-load: true
      on-chunk-unload: true
      after-x-ticks:
        # removes wither skulls after x ticks of it being launched by a wither
        enable: true
        ticks: 200 # 10 seconds
      # removes all wither skulls every 20 ticks
      remove-all-flying-skulls: false
    disable-wither-spawning-at-spawn:
      enable: false
      # configure message in lang.yml
      inform-players: true
      # worldname: radius
      worlds:
        world: 5000
        world_nether: 5000
        world_the_end: 5000

dupe-preventions:
  prevent-chests-on-living-entities: false
  prevent-chested-living-entities-in-portals: true
  prevent-end-portal-dupe: true
  # Not sure if this works, please try it
  experimental-dupe-patch-1: false
  # I don't know if this works, someone on discord said I should prevent the mobs
  # from despawning if they are 500 blocks near a player.
  # Automatically disabled in non 1.12 because it causes a SHIT ton of mobs to spawn:
  # https://i.imgur.com/f691cep.png and disabled by default in the config because a
  # shit ton of enderman spawn
  experimental-dupe-patch-2: false

illegals:
  remove-placed-blocks:
    on-chunkload:
      # Note that this has impact on your TPS if there are a lot of illegal blocks to remove.
      enable: false
      # You can enter PLAYER_HEAD here if you want to remove placed playerheads.
      # NOTE: this ONLY applies to player_head. for everything else you have to use
      # correct Material enums for your minecraft version.
      blocks-to-remove:
        - BEDROCK
        - BARRIER
        - COMMAND
        - STRUCTURE_BLOCK
        - PLAYER_HEAD
      pause-on-low-TPS: true
      pause-TPS: 14
      exempted-worlds:
        - 'exampleworld1'
        - 'exampleworld2'
    periodically:
      enable: false
      # You can enter PLAYER_HEAD here if you want to remove placed playerheads.
      # NOTE: this ONLY applies to player_head. for everything else you have to use
      # correct Material enums for your minecraft version.
      blocks-to-remove:
        - BEDROCK
        - BARRIER
        - COMMAND
        - STRUCTURE_BLOCK
        - PLAYER_HEAD
      check-period-in-seconds: 5
      pause-on-low-TPS: true
      pause-TPS: 14
      exempted-worlds:
        - 'exampleworld1'
        - 'exampleworld2'
  remove-unnatural-spawners-on-chunkload:
    enable: false
    pause-on-low-TPS: true
    pause-TPS: 14
    # You can add more worlds, rename worlds, remove worlds at will here :)
    natural-spawner-types-per-world:
      world:
        - SKELETON
        - ZOMBIE
        - SILVERFISH
        - SPIDER
        - CAVE_SPIDER
      world_nether:
        - BLAZE
        - MAGMA_CUBE
      world_the_end:
        - SKELETON
        - SPIDER
  spawn-eggs:
    remove-spawn-eggs: true
    prevent-using: false
  player-heads:
    remove-items: true
  revert-overstacked-items:
    enable: true
    item-whitelist-enabled: false
    use-as-blacklist-instead: false
    delete-shulker-if-contains-overstacked: false
    periodically-check-player-inventories:
      enable: false
      check-period-in-ticks: 20
    whitelisted-items:
      - TOTEM
  enchantments:
    revert-unenchantables:
      enable: true
      item-whitelist-enabled: true
      use-as-blacklist-instead: false
      delete-shulker-if-contains-unenchantable: false
      periodically-check-player-inventories:
        enable: false
        check-period-in-ticks: 20
      whitelisted-items:
        - "GOLDEN_APPLE"
    revert-overenchanted:
      enable: true
      item-whitelist-enabled: true
      use-as-blacklist-instead: false
      delete-shulker-if-contains-overenchanted: false
      periodically-check-player-inventories:
        enable: false
        check-period-in-ticks: 20
      whitelisted-items:
        - "GOLDEN_APPLE"
    revert-multiply-enchanted:
      enable: true
      item-whitelist-enabled: true
      use-as-blacklist-instead: false
      periodically-check-player-inventories:
        enable: false
        check-period-in-ticks: 20
      whitelisted-items:
        - "BOW"
    revert-specific-overenchants:
      enable: false
      # You need to use correct Enchantment enums for your version.
      enchantments:
        - "DIG_SPEED"
      item-whitelist-enabled: true
      use-as-blacklist-instead: false
      delete-shulker-if-contains-overenchanted: false
      periodically-check-player-inventories:
        enable: false
        check-period-in-ticks: 20
      whitelisted-items:
        - "GOLDEN_APPLE"
  revert-unbreakables:
    # Revert unbreakable items, items with less than 0 durability will be automatically removed or set to 0 durability,
    # which will break on the next use. Items with higher than max durability will be set to legal maximum durability.
    enable: true
    item-whitelist-enabled: true
    use-as-blacklist-instead: false
    # Deletes the shulker if it contains an unbreakable (respects whitelist/blacklist)
    delete-shulker-if-contains-unbreakable: false
    periodically-check-player-inventories:
      enable: false
      check-period-in-ticks: 20
    whitelisted-items:
      - "DIAMOND_CHESTPLATE"
    skip-zero-durability: true # Make sure to keep enabled, otherwise netherite tools will mistakenly be set to maximum durability, due to some bug in spigot.
  banned-blocks:
    # You need to use correct Material Enums for your Minecraft Version here.
    banned-blocks:
      - BEDROCK
      - BARRIER
      - COMMAND
      - STRUCTURE_BLOCK
      - ENDER_PORTAL_FRAME
    remove-items: true
    prevent-placing: true
    # If enabled, checks shulker for banned blocks and deletes the shulker if found.
    delete-shulker-if-contains-banned-block: false
    periodically-check-player-inventories:
      enable: false
      check-period-in-ticks: 20
  remove-items-with-specific-names:
    # Remove items that were custom named to a specific string. Suggested by STORMIN.
    enable: false
    item-names:
      - "Super Insane Mega Sussy Item" # case sensitive
  remove-items-with-specific-data-values: # 1.12 only
    enable: false
    data-values:
      - "SuperIllegalItem(0)"
  remove-illegal-golden-apples: false # 1.12 only

redstone:
  rate-limit-levers:
    enable: false
    show-actionbar: true
    # configure message in lang.yml
    kick-player: false
    lever-uses-per-time: 5
    time-in-ticks: 60
  disable-redstone-on-low-tps:
    enable: false
    log: true
    disable-TPS: 16.0

chunk-limits:
  exp-bottle-limit:
    # Prevent having a shit ton of exp bottles in one chunk then loading it to kill the server
    enable: false
    # Max in a chunk, doesn't limit the actual xp orbs.
    max-exp-bottle-per-chunk: 25
  vehicle-limit:
    # Prevent lag using minecarts / boats / horses / etc.
    enable: false
    max-vehicles-per-chunk: 25
    check-period-in-ticks: 200
  entity-limits:
    non-living-limit:
      enable: false
      log-removals: true
      max-non-living-per-chunk: 100
      check-period-in-ticks: 20
    custom-limit:
      enable: false
      log-removals: true
      check-period-in-ticks: 20
      # Uses EntityTypes
      limited-types:
        WITHER: 16
        COW: 10
        CHICKEN: 10
        HORSE: 5
        SKELETON_HORSE: 5
        DONKEY: 5
  block-limit:
    enable: true
    max-blocks-per-chunk:
      # you need to use correct Material enums depending on your version here
      ENCHANTMENT_TABLE: 16
      ENDER_CHEST: 64
      CHEST: 500
      DISPENSER: 100
      TRAPPED_CHEST: 200
      SIGN: 100
      SLIME_BLOCK: 128
      BEACON: 32
      PISTON_BASE: 32
      PISTON_EXTENSION: 32
      PISTON_MOVING_PIECE: 32
      PISTON_STICKY_BASE: 32
      GLOWSTONE: 5000
      BANNER: 100
      SKULL: 50
      SKULL_ITEM: 50
  falling-block-limit:
    enable: true
    # Prevent massive sand chunks from killing the server, prevents any
    # falling blocks from falling if there is more than 50 falling blocks in a chunk
    max-gravitiy-blocks-per-chunk: 50
    disable-falling-blocks-on-low-TPS:
      enable: true
      disable-TPS: 16.0

elytra:
  packet-elytra-fly:
    # Patches the future/rusherhack/kamiblue 2b2t elytra fly exploit
    patch-packet-elytra-fly: true
    # Will only allow players to go about 85km/h on kami blue, and won't even work on rusherhack.
    # Recommended to not go lower as there could be false positives.
    max-elytra-opens-per-10-seconds: 25
    # If enabled, will tell the player to disable packet elytra fly in actionbar
    # Configure notify message in lang.yml
    notify-player-to-disable-packetfly: true
    # If enabled, the plugin will not remove elytra from the player, but simply disconnect from the server.
    # Will use notify message as kick message
    kick-instead-of-remove-elytra: false
  elytra-speed: # set nocheatplus horizontal elytra settings to 999999
    # Display infos in actionbar while flying
    display-actionbar: true
    # Inform flying player if they are in old or new chunks
    display-chunk-info-in-actionbar: true
    Global-Settings:
      # Global settings. If nothing else is enabled, this will be used for all cases.
      enable: true
      deny-elytra-usage: false
      speed-old-chunks: 1.81 # 130km/h
      speed-new-chunks: 1.81 # 130km/h
      enable-bursting: true
      burst-speed-old-chunks: 5.0 # 357km/h
      burst-speed-old-chunk-TPS: 18.0
      burst-speed-new-chunks: 3.12 # 223km/h
      burst-speed-new-chunk-TPS: 19.0
      deny-elytra-on-low-TPS: true
      deny-elytra-TPS: 12
      also-remove-elytra-on-low-TPS: true
    Nether-Ceiling:
      # Use seperate values for players above the nether ceiling.
      enable: true
      deny-elytra-usage: false
      speed-old-chunks: 0.5
      speed-new-chunks: 0.5
      enable-bursting: false
      burst-speed-old-chunks: 1.0
      burst-speed-old-chunk-TPS: 18.0
      burst-speed-new-chunks: 1.0
      burst-speed-new-chunk-TPS: 18.0
      deny-elytra-on-low-TPS: true
      deny-elytra-TPS: 12.0
      also-remove-elytra-on-low-TPS: true
    At-Spawn:
      # Use seperate values for players at spawn.
      enable: false
      deny-elytra-usage: false
      radius: 3000
      speed-old-chunks: 1.0
      speed-new-chunks: 0.8
      deny-elytra-on-low-TPS: true
      deny-elytra-TPS: 10.0
      also-remove-elytra-on-low-TPS: true

bedrock:
  prevent-going-below-bedrock-floor: true
  fill-in-bedrock:
    # Now working on 1.12+ without errors
    overworld-floor:
      # Set this to -64 if you're on 1.18+ or any number you want if you're using a custom generator
      min-floor-y: 0
      # enter world names that should be skipped (useful if you're using skyland generators for ex.)
      exempted-worlds:
        - exampleworld
        - exampleworld2
      fill-on-chunkload:
        enable: false
        also-check-new-chunks: false
        pause-on-low-tps: true
        pause-tps: 16.0
      periodically-check-and-fill:
        # only checks loaded chunks
        enable: false
        check-period-in-seconds: 10
        pause-on-low-tps: true
        pause-tps: 16.0
    nether-floor:
      min-floor-y: 0
      exempted-worlds:
        - exampleworld
        - exampleworld2
      fill-on-chunkload:
        enable: false
        also-check-new-chunks: false
        pause-on-low-tps: true
        pause-tps: 16.0
      periodically-check-and-fill:
        enable: false
        check-period-in-seconds: 10
        pause-on-low-tps: true
        pause-tps: 16.0
    nether-ceiling:
      max-ceiling-y: 127
      exempted-worlds:
        - exampleworld
        - exampleworld2
      fill-on-chunkload:
        enable: false
        also-check-new-chunks: false
        pause-on-low-tps: true
        pause-tps: 16.0
      periodically-check-and-fill:
        enable: false
        check-period-in-seconds: 10
        pause-on-low-tps: true
        pause-tps: 16.0

chat:
  fix-ChatCo-ignore-bug: false
  replace-@: true
  prevent-unicode-dot: true
  character-limit:
    enable: true
    log: true
    char-limit: 128
  links:
    prevent-sending:
      enable: false
      log: true
      only-for-players-around-spawn: true
      spawn-radius: 1000
      link-regex:
        - "(https?://(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?://(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})"
        - "[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z()]{1,6}\\b([-a-zA-Z()@:%_+.~#?&/=]*)"
      more-lenient-link-check:
        enable: true
        exemptions:
          - "discord"
          - "dc"
    prevent-spamming:
      enable: true
      delay-until-next-link-in-seconds: 300
      only-for-players-around-spawn: true
      spawn-radius: 1000
      link-regex:
        - "(https?://(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?://(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})"
        - "[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z()]{1,6}\\b([-a-zA-Z()@:%_+.~#?&/=]*)"
      more-lenient-link-check:
        enable: true
        exemptions:
          - "discord"
          - "dc"
  banned-words:
    enable: false
    log: true
    banned-words:
      - "what's 2+2"
  banned-regex:
    enable: false
    log: true
    banned-regex:
      - "^This is a(.*)banned message" # Prevents any message that starts with "This is a" and ends with "banned message"
  prevent-spam:
    enable: false
    log: false
    anti-spam-time: 1 # 1 message per second
    # How many messages should we allow to send in x seconds (converted to ticks)
    anti-spam-check-time: 30
    anti-spam-messages-per-time: 10 # ~1 message every 3 seconds if constantly spamming
    anti-spam-word-time: 60
    anti-spam-commands:
      enable: false
      log: true
      anti-spam-command-time: 1
      use-whitelist: true # Exclude commands from antispam.
      whitelist:
        - /msg
        - /message
        - /w
        - /whisper
        - /tell
        - /r
        - /reply
        - /last
  command-whitelist:
    # This will make it pretty much impossible to find your plugins as only the commands you specify will be able to work.
    # allow bypass using permission: anarchyexploitfixes.commandwhitelistbypass
    enable: false
    use-as-blacklist-instead: false
    commands:
      - /help
      - /vote
      - /kill
      - /discord
      - /togglechat
      - /toggleconnectionmsgs
      - /toggletells
      - /togglewhispering
      - /toggleprivatemsgs
      - /ignore
      - /ignorelist
      - /ignorehard
      - /toggledeathmsg
      - /dmt
      - /stats
      - /worldstats
      - /tps
      - /msg
      - /whisper
      - /w
      - /m
      - /t
      - /pm
      - /tell
      - /r
      - /reply
      - /last

1b1t-options:
  enable-slowdupe: false
  1b1t-place-bedrock: false
  use-spark-health: false
  nick-reset-only: false
  distance-away-to-teleport:
    enable: false
    distance-in-blocks: 5000
    teleport-commands:
      - /tpa
      - /tpahere
      - /call
      - /ecall
      - /etpa
      - /tpask
      - /etpask
    excluded-worlds:
      - world_the_end
      - exampleworld2
  make-specific-commands-hurt-you:
    enable: false
    hurt-commands:
      - /tpa
  disable-ncp-geyser: false
  bypass-slots: false

config-version: 1.0