name: AnarchyExploitFixes
version: ${project.version}
main: me.moomoo.anarchyexploitfixes.Main
description: ${project.description}
softdepend: [ ProtocolLib ]
api-version: 1.12

commands:
  aef:
    usage: /<command>
    description: AnarchyExploitFixes commands